version: '2'
services:
  config:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      CONFIG_SERVICE_PASSWORD: user
#    image: sqshq/piggymetrics-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    build: config
    ports:
       - 8888:8888

  registry:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-registry
    build: registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-gateway
    build:  gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  hello-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: user
#      ACCOUNT_SERVICE_PASSWORD: user
#      MONGODB_PASSWORD: $MONGODB_PASSWORD
#    image: sqshq/piggymetrics-account-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    build: hello-service
    ports:
      - 6000:6000

  auth-service:
#    image: sqshq/piggymetrics-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    build: auth-service
    ports:
      - 5000:5000
