logging:
  level:
    org.springframework.security: DEBUG
    com.rinat.hello.client: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  rabbitmq:
    host: rabbitmq