server:
  context-path: /hello
  port: 6001

security:
  oauth2:
    client:
      clientId: hello-service
      clientSecret: secret
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
management:
  security:
    enabled: false